name: Rust

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        name: Build (rust-prisma)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Generate prisma client
              run: cargo prisma generate
            - name: Build
              run: cargo build --verbose
            - name: Run tests
              run: cargo test --verbose
